#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tangram
version:      2.06
version_from: Tangram.pm
installdirs:  site
requires:
    Test::More:                    0
    Set::Object:                   1.03
    DBI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
